-- ACCOUNT STATUS CHECK

CREATE TRIGGER [dbo].[STATUSCHECK]
ON account
AFTER UPDATE
AS
SET NOCOUNT ON
BEGIN TRY
DECLARE @BALANCE INTEGER
DECLARE @USERID INTEGER

SELECT @USERID = i.accountid
FROM inserted i
WHERE i.astatus NOT LIKE 'BANK'

SELECT @BALANCE = a.balance
FROM account a
WHERE a.accountid = @USERID

IF (@BALANCE >= 50000)
BEGIN
UPDATE account
SET astatus = 'VIP'
WHERE accountid = @USERID
END

ELSE IF (@BALANCE < 50000)
BEGIN
UPDATE account
SET astatus = 'STANDARD'
WHERE accountid = @USERID
END
END TRY

BEGIN CATCH
ROLLBACK
DECLARE @ERRORMSG VARCHAR(2000)
SET @ERRORMSG = ERROR_MESSAGE()
PRINT @ERRORMSG
END CATCH


 -- BANK BALANCE TRIGGER

CREATE TRIGGER [dbo].[BANKBALANCECHECK]
ON account
AFTER UPDATE
AS
SET NOCOUNT ON
BEGIN TRY
DECLARE @BALANCE INTEGER

SELECT @BALANCE = a.balance
FROM account a
WHERE a.accountid = 0

IF (@BALANCE < 100000)
BEGIN
UPDATE account
SET balance = 1000000
WHERE accountid = 0
END
END TRY

BEGIN CATCH
ROLLBACK
DECLARE @ERRORMSG VARCHAR(2000)
SET @ERRORMSG = ERROR_MESSAGE()
PRINT @ERRORMSG
END CATCH


-------------------------------------------------------------